<?php

namespace Blog\BlogBundle\Repository;

/**
 * MesartiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesartiRepository extends \Doctrine\ORM\EntityRepository
{
}
